### ISSUE TITLE
Commision list not updating on date switch

### ISSUE THREAD

**Issue by hllwrld7** [ItsSpyce/dailies-tracker#26]
**Describe the bug**
When I switch the date, the commission list is not updating.

**To Reproduce**

1. Add a new commission
2. Change the date on the calendar
4. The commission list is not updating

**Expected behavior**
When I switch the date, the commission list should update, so, for example, if I added a commission on 19.05 and then changed date to 20.05 and it should have commissions that I have on this day (if any), and not the commissions for 19.05.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version: Windows 11 23H2

**Additional context**
Idk I might've broken something because I was messing with my pc's datetime to reproduce the bug I previously reported, but the only thing I did was to change the date for the next day.

**Comment by hllwrld7** [comment]
ok, I think I actually have broken smth because marking commissions as complete isn't updating the tasks number, but I distinctly remember that it worked before............ idk what I did wrong tho
I'll see if I can fix it on my end

**Comment by hllwrld7** [comment]
Ok, I should not be able to view my commissions for any other date that is not today, correct?

**Comment by ItsSpyce** [comment]
The commission list will stay the same, only the checkbook will change.

**Comment by hllwrld7** [comment]
Oh, okay, I see, thanks! I'll close it then since I guess it's not an actual bug

**Comment by ItsSpyce** [comment]
If you'd like, I can add a filter on created_at so they don't show up!
