### ISSUE TITLE
App starts to blank page when not in dev mode

### ISSUE THREAD

**Issue by justjustie** [ItsSpyce/dailies-tracker#4]
**Describe the bug**
Starting with 070040d at the latest, building and running the app starts it to a blank page only. It works when ran via `npm run dev` or `wails dev`.

**To Reproduce**
1. Build using `wails build` in `packages/app`
2. Run `packages\app\build\bin\Dailies Tracker.exe`

**Expected behavior**
App starts as usual, UI is shown

**Desktop (please complete the following information):**
 - Windows 11
 - go1.22.2
 - Wails CLI v2.8.1

**Additional context**
Was not reproducible on go1.21.6 by @ItsSpyce, so maybe it's that

**Comment by ItsSpyce** [comment]
Was able to reproduce using the steps you provided! I'll take a look into it

**Comment by ItsSpyce** [comment]
After digging in further, it's something to do with styled-components not setting the theme properly. Will need to see if it's an issue with Vite or with how I setup the theme

**Comment by ItsSpyce** [comment]
Bug seems to be fixed as of the latest changes. I reverted `styled-components` down to a sticky version of 5 and it appears to have resolved it. Not sure if it's improperly setting the theme but the benefits from 6 don't really showcase here

**Comment by justjustie** [comment]
Tested with 266ffd3, works as expected again!
